### ISSUE TITLE
Cloned atlases not updated simultaneously in SMP

### ISSUE THREAD

**Issue by Hunternif** [AntiqueAtlasTeam/AntiqueAtlas#45]
Situation: Bob and Alice have clones of the same atlas. Bob walks away, and his atlas is updated with newly explored terrain, but Alice's copy will not be updated until she reconnects to the server.

**Comment by Hunternif** [comment]
This will require a separate sync packet for tiles only (not a full NBT tag, without the browsing position, see #48), and some mechanism to mark which new locations have been sync'ed for which players holding the cloned items. As a last resort, we can simply send all new data after the cloning point to all players without discretion.

**Comment by Kenkron** [comment]
I've got a new type of packet for #48, so I like to think this won't be too hard now

**Comment by Kenkron** [comment]
pau101 pointed out that doing map updates server side instead of client side would eliminate the need for the client to send `PutBiomeTilePacket`s to the server. This would require the server to send packets to the client instead, eliminating one of the problems outlined in #133, and making simultanious terrain updates in SMP easier.

**Comment by Kenkron** [comment]
As of 80fb82cbff31b59ca8367ffff7201c19cbad5706, dimension data updates in real time.  Still working on markers.

**Comment by Kenkron** [comment]
Turns out markers already update simultaneously SMP. DONE!
