### ISSUE TITLE
Player Tracking applied to different Atlas instances

### ISSUE THREAD

**Issue by Zsashas** [AntiqueAtlasTeam/AntiqueAtlas#58]
I click the icon, it tracks me on the map, I close it, and when I next open it, tracking is turned off again. I don't think it did this before. Using latest version.

**Comment by Hunternif** [comment]
Need to decide: should player tracking status be remembered for separate atalses? Should the server remember it or only the client?

**Comment by Hunternif** [comment]
Use cases:
1. Most common. Player only has one atlas, checks frequently to see where he is going, tracking is on most of the time.
2. Player has 2 atlases: A for navigation with tracking on, and B only has the destination explored (by someone else, or given as part of a quest in future. The terrain may even look different.). He would look at B to see if he has reached the destination. B would therefore need to always show the same location, and A should track the player.
This configuration should be remembered on the server, but can't be part of AtlasData, because other players might have clones of this atlas.

**Comment by Hunternif** [comment]
For now player tracking option is simplified, but this issue will have to be considered again in future.

**Comment by Kenkron** [comment]
a7edbfb fixes this from the looks of it.
