### ISSUE TITLE
Empty field where Ice Spikes should be

### ISSUE THREAD

**Issue by mankra** [AntiqueAtlasTeam/AntiqueAtlas#94]
Minecraft: 1.10.2
Forge: 12.18.2.2147
Antique Atlas: 4.3.0

![2016-11-24_23 34 40](https://cloud.githubusercontent.com/assets/22047030/20610781/f9308774-b29e-11e6-8402-d91fc8833a0c.png)

In biome_textures.json, the biome ID 140 has the value "ICE_SPIKES", which is correct afaik.

**Comment by Kenkron** [comment]
thanks for pointing this out. Some of the textures are missing.

**Comment by ghost** [comment]
I made my own version of Golriths textures for my private modpack:

[AABOP-mk.zip](https://github.com/Hunternif/AntiqueAtlas/files/691415/AABOP-mk.zip)

but I couldn't figure out which textures are missing because the PNGs are there. Maybe you want to integrate the texture pack into your mod (if permitted). I slightly altered some pics and added a few, nothing great.
