### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Jordsterman** [AntiqueAtlasTeam/AntiqueAtlas#97]
I'm running a private white-listed server for me and a few friends and I'm getting this error. java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes

**Comment by Hunternif** [comment]
I'm sorry about your troubles.
This probably happened because an atlas grew too large and couldn't be sent in a single packet. This will be fixed in the future, but as a temporary solution, if you want to continue playing on this server, you can try deleting the data for the offending atlas. If you go to your server's world folder, then in the folder `data` you should find a bunch of files named `aAtlas_#.dat`. Delete the largest one and see if that helps.

**Comment by Kenkron** [comment]
I've got a branch for it (This is part of #48 ), and hopefully I can get that fixed over Christmas.
